# Generated by Django 5.1.4 on 2024-12-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
