# Generated by Django 5.1.4 on 2024-12-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='newsroom.tag'),
        ),
    ]
